---
- name: Update package index
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Install OpenJDK (Java 17 or 21)
  apt:
    name: openjdk-{{ openjdk_version | default('17') }}-jdk
    state: present

- name: Get JAVA_HOME path
  shell: |
    readlink -f $(which java) | sed "s:bin/java::"
  register: java_home_path
  changed_when: false

- name: Set Java environment (JAVA_HOME)
  lineinfile:
    path: /etc/environment
    line: JAVA_HOME="{{ java_home_path.stdout }}"
    state: present

- name: Reload environment variables
  shell: source /etc/environment
  args:
    executable: /bin/bash
  changed_when: false

- name: Verify Java version
  command: java -version
  register: java_version_output
  failed_when: false
  changed_when: false

- name: Show Java version
  debug:
    msg: "Java version is: {{ java_version_output.stdout }}"